# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy: 
  matrix: 
    linux:
      operatingSystem: 'ubuntu-latest' 
pool:
  vmImage: $(operatingSystem)

# Pipelines > Stages > Jobs > Tasks(Steps)

steps:
- script: echo Running on $(operatingSystem) - Hello, world, changed!
  displayName: 'Run a one-line script'
