# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# strategy: 
#   matrix: 
#     linux:
#       operatingSystem: "ubuntu-latest"
pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Tasks(Steps)

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'deploy to Dev'
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'deploy to QA'

# steps:
# - script: echo Running on $(operatingSystem) - Hello, world, changed!
#   displayName: 'Run a one-line script'
