trigger:
- master

# pool:
#   vmImage: 'ubuntu-latest'

# resources:
# - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'EVN-EVN0031-W01'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker hub connection'
        repository: 'in28min/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        
    
    