# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Pipelines > Stages > Jobs > Tasks(Steps)

stages: 
  - stage: Build
    jobs: 
    - job: FirstJob
      steps: 
      - bash: echo Build First Job
      - bash: echo Directory Artifact $(Build.ArtifactStagingDirectory) 
      - bash: echo Enviroment Name $(Environment.Name)
      - bash: echo AccessToken Enviroment $(System.AccessToken)
      - bash: echo Build Number $(Build.BuildNumber)
      - bash: echo SourceBranchName $(Build.SourceBranchName)
      - bash: echo SourceDirectory $(Build.SourcesDirectory)
      - bash: echo ArtifactStagingDirectory $(Build.ArtifactStagingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: java -version

    # - job: SecondJob
    #   steps: 
    #   - bash: echo Build First Job 
  # - stage: DevDeploy
  #   dependsOn: Build
  #   jobs: 
  #   - job: DevDeployJob
  #     steps: 
  #     - bash: echo $(envoroment)DevDeployJob
  # - stage: QADeploy
  #   dependsOn: Build
  #   jobs: 
  #   - job: QADeployJob
  #     steps: 
  #     - bash: echo QADeployJob
  # - stage: ProdDeploy
  #   dependsOn: 
  #   - Build
  #   - DevDeploy
  #   - QADeploy
  #   jobs: 
  #   - job: ProdDeploy
  #     steps: 
  #     - bash: echo ProdDeploy
